version: "3.9"

services:

  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka
    ports:
      - "8761:8761"

  customer-service:
    build:
      context: .
      dockerfile: ./Banking.CustomerService/Dockerfile
    container_name: customer-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - eureka

  account-service:
    build:
      context: .
      dockerfile: ./Banking.AccountService/Dockerfile
    container_name: account-service
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - eureka

  gateway:
    build:
      context: .
      dockerfile: ./Banking.Gateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - customer-service
      - account-service